services:
  bd:
    image: postgres:18.0-alpine3.22
    container_name: bd
    ports:
      - 11432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bd
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./:/data
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
volumes:
  postgres_data: